name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  workflow_dispatch: # Allows manual execution

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git
        run: |
          git config --global user.email "mahiattri004@gmail.com"
          git config --global user.name "mahi-attri"

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://huggingface.co/spaces/mahiattri/infosys_training
          git push --force "https://user:$HF_TOKEN@huggingface.co/spaces/mahiattri/infosys_training" main
